name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: ['.github/**']
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Display event and branch information
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "🔎 The name of your branch is ${{ github.head_ref }}"
          else
            echo "🔎 The name of your branch is ${{ github.ref }}"
          fi
          echo "Your repository is ${{ github.repository }}."

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
